# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bitazza' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bitazza
  pod 'keyri-pod'

  target 'BitazzaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitazzaUITests' do
    # Pods for testing
  end

end
